### ISSUE TITLE
Is there an API for Method of Morris?

### ISSUE THREAD

**Issue by kdavies4** [jdherman/SALib#35]
This isn't an issue but a question or two. Is there an API for interfacing with SALib.sample.morris and SALib.analyze.morris, without the need to read and write parameter files, sample files, and model results? Is it possible to get the analysis results directly without using the operating system to write it to a file and then read it later?

**Comment by jdherman** [comment]
Great question. When I initially started this, it was focused on models written in other languages ... so everything was done with the CLI and files. But several other people have mentioned the need to improve the python interface.

This is a longer-term update, but it's one I'd really like to do. The way I see it, the following things should happen:
* Sampling routines should accept either a parameter file, or a dictionary of parameter names/bounds
* Sampling routines should return a numpy matrix
* Analysis routines should accept either input/output files, or numpy matrices.

It's already possible to get the sensitivity indices from the analysis functions, though. They return a dictionary of the indices (here's [one of the examples](https://github.com/jdherman/SALib/blob/master/examples/morris/morris.py)).

**Comment by kdavies4** [comment]
I agree with your 3 bullet points. If those features become available, I'll use them, especially number 2 and 3.

Thanks for the link to the example. I'm now receiving the sensitivity indices directly.

**Comment by jdherman** [comment]
Hi @kdavies4, I added bullet points 1-2 in #33. So now the Morris sampling method will return a numpy matrix, and you can (optionally) define the parameter bounds in a python dictionary rather than a separate parameter file. Example here:
https://github.com/jdherman/SALib/blob/master/examples/morris/morris.py

These updates aren't on pypi yet. I'll look into bullet point 3 but that will be a longer-term update ... I'm going to close this for now.
